<!DOCTYPE HTML>
<html>
<head>
    <title>Главная страница</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="script" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js">
    <link rel="stylesheet" href="../static/css/styleHeader.css">
    <link rel="stylesheet" href="../static/css/main.css">

</head>
<header >
    <div class="d-flex flex-column flex-md-row align-items-center mb-4">
        <a href="/main">
            <img src="https://i.imgur.com/FdWY2zN.png" class="logo">
        </a>

        <ul class="nav nav-pills_s">
            <li class="nav-item"><a href="/main" class="nav-link active" aria-current="page">Главная</a></li>
            <li class="nav-item"><a href="/schedule" class="nav-link">Расписание</a></li>
            <li class="nav-item"><a href="/about" class="nav-link">О нас</a></li>
        </ul>
    </div>
</header>